### PR TITLE
Fix a typo.

### PR DESCRIPTION
**Pull request by mahiuchun**

### CODE REVIEW

**Comment by lag-linaro** [comment]
Can you be more descriptive in your commit message please?

It should have a proper title and explain what you're changing and why.

**Comment by lag-linaro** [comment]
Something like:

```
README: Scripts: Fix incorrect spelling of Lenovo platform 'Miix'

In some cases it was accidentally spelt 'Mixx'.
```

**Comment by mahiuchun** [comment]
Done.

**Comment by lag-linaro** [comment]
Applied, thanks. :+1:

**Pull request merged**
